//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ID { get; set; }
        public string PRONAME { get; set; }
        public Nullable<double> PRICE { get; set; }
        public byte[] POSTER { get; set; }
        public int INSTOCT { get; set; }
        public Nullable<int> QUANTITY { get; set; }
    }
}
